version: '2.1'
services:
  nginx:
    extends:
      file: ./docker/nginx/nginx-service.yml
      service: nginx
    depends_on:
      sslgenerator:
        condition: service_healthy
  sslgenerator:
    extends:
      file: docker/sslgenerator/sslgenerator-compose.yml
      service: sslgenerator