version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./conf/mutual.tls.default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/ca/ca.crt:/opt/ca.crt
      - ./certs/server/client-ssl.fraber.com.key:/opt/client-ssl.fraber.com.key
      - ./certs/server/client-ssl.fraber.com.crt:/opt/client-ssl.fraber.com.crt