version: '2.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./conf/mutual.tls.default.conf:/etc/nginx/conf.d/default.conf
      - ../sslgenerator/workdir/certificates/client/caclient.crt:/opt/ca.crt
      - ../sslgenerator/workdir/certificates/server/caserver.key:/opt/client-ssl.fraber.com.key
      - ../sslgenerator/workdir/certificates/server/caserver.crt:/opt/client-ssl.fraber.com.crt